### ISSUE TITLE
 Library not loaded: '@loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon'

### ISSUE THREAD

**Issue by eliselavy** [arielm/chronotext-cross#2]
I try to run the Hello World example https://arielm.github.io/cross-blog/2022/10/06/hello-world.html for a macOS 's user.
Here is my configuration:
<img width="335" alt="Screenshot 2022-12-16 at 12 09 07" src="https://user-images.githubusercontent.com/35602279/208085651-4de6718a-3a20-4aff-937f-7fa4874dc58d.png">

I met the following error:

```
1: Test timeout computed to be: 600
1: dyld[23297]: Library not loaded: '@loader_path/../Frameworks/Syphon.framework/Versions/A/Syphon'
1:   Referenced from: '--/chronotext-cross/tests/TestingTriangle/build/osx/TestingTriangle'
1:   Reason: tried: '--/chronotext-cross/tests/TestingTriangle/build/osx/../Frameworks/Syphon.framework/Versions/A/Syphon' (no such file), '/Library/Frameworks/Syphon.framework/Versions/A/Syphon' (no such file), '/System/Library/Frameworks/Syphon.framework/Versions/A/Syphon' (no such file)
1: --/chronotext-cross/tests/TestingTriangle/build/osx/run.sh: line 3: 23297 Abort trap: 6           ./TestingTriangle "$@"
1/1 Test #1: TEST_ALL .........................***Failed    0.33 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.33 sec

The following tests FAILED:
	  1 - TEST_ALL (Failed)
CMake Error at --/chronotext-cross/core/cmake/run.cmake:62 (message):
  TEST FAILED!
```

A suggestion?

**Comment by arielm** [comment]
Hi there!

I recently introduced support for Syphon, but I apparently not tested the system enough. Sorry for the inconvenience.

I have a quick workaround:
```
cd $CROSS_PATH/tree/syphon
sudo cp -R Syphon.framework /Library/Frameworks
```
This will install the tiny Syphon framework on your machine, and then `TestingTriangle` should work just fine.

I will try to come up with a better solution (will update this thread whenever it's ready...)

**Comment by eliselavy** [comment]
Hi Ariel

Works perfectly :pray: - Such a beautiful portofolio :clap:

**Comment by arielm** [comment]
Update: I could not find a simpler way than what I proposed as a solution. I updated the docs accordingly.
